### ISSUE TITLE
Legend at bottom

### ISSUE THREAD

**Issue by mikaoelitiana** [CodeYellowBV/chartist-plugin-legend#10]
Is it possible to place legend box at bottom instead of top. More generally, that would be great to be able to set position in options (right, left, top, bottom)

**Comment by SpaceK33z** [comment]
With CSS you can place it anywhere you want it to be. I could make it possible to provide a custom CSS class to the legend, so it's easier to change this.

**Comment by mikaoelitiana** [comment]
Ok thanks

**Comment by vishalbisa** [comment]
Hi @SpaceK33z ,

Can you please provide a custom CSS class to the legend,
