### ISSUE TITLE
On Pie charts, filtering values clicking legend fields not respect colors

### ISSUE THREAD

**Issue by karlos1337** [CodeYellowBV/chartist-plugin-legend#11]
It happens even in the demo, if you click the first legend field the second field takes his name and color (and the third become the second ... etc) and legend colors dont change according that.

In others charts like bars dont happens, if you remove one color the other values remains theirs colors.

**Comment by SpaceK33z** [comment]
Good catch, you are right. Don't have time to fix this soon, a PR is welcome.

**Comment by SpaceK33z** [comment]
It should be fixed now. There still is one big bug with the labels in a pie that I didn't manage to fix yet; if you use labels and click a few times on the legend, the labels will be displayed incorrectly.

A workaround for this is to pass the labels to `legendNames`, then it should work fine.

**Comment by SpaceK33z** [comment]
Okay the bug I mentioned above should also be fixed now. Published version `0.3.1`.
