### ISSUE TITLE
NPM latest version differs from 0.2.1 tag

### ISSUE THREAD

**Issue by ealves-pt** [CodeYellowBV/chartist-plugin-legend#12]
I'm installing this using `npm i chartist-plugin-legend --save` and the version that is installed belongs to the tag `0.2.0` and not the `0.2.1`. But the weird thing is that the `package.json` says that the version installed is the `0.2.1`.

I've noticed that because the AMD is not working due to the missing `Chartist` argument in the factory function.

**Comment by SpaceK33z** [comment]
I just released `0.2.2`, can you try again?

**Comment by ealves-pt** [comment]
Perfect. Version `0.2.2`fixed my issue.

:+1:
