### ISSUE TITLE
When there are multiple charts on a page, only 1 legend gets rendered.

### ISSUE THREAD

**Issue by paul-apacio** [CodeYellowBV/chartist-plugin-legend#17]
As in my subject.  I have multiple charts on my page, but the legend only gets rendered once for the whole page.

**Comment by SpaceK33z** [comment]
https://codeyellowbv.github.io/chartist-plugin-legend/

In the demo this appears to be working...

**Comment by paul-apacio** [comment]
I should clarify, when there is more than one of the same chart.

-Paul

**Comment by aualdrich** [comment]
@paul-apacio Did you ever find a workaround to this? I'm having the same issue.

**Comment by t2** [comment]
This seems like a big flaw. We have a dashboard of multiple Chartist charts and needs legends for each. Did you ever find a way to resolve this @paul-apacio?

**Comment by SpaceK33z** [comment]
I'm working on a fix right now.

**Comment by paul-apacio** [comment]
My resolution was to simply render the legends separate to the chart as plain html, as I was passing the data in at render time, so it was available to me.

**Comment by SpaceK33z** [comment]
@aualdrich, @t2, can you share an example of when this is happening? I added a test (61ed13e33d1a4e1a8e5d559ac358431a6896961d) to try to reproduce it, but it appears to work...

**Comment by michalchovanak** [comment]
Hi, i am having the same issue. I have 3 charts in a slick.js slider and only one renders the legend.

**Comment by SpaceK33z** [comment]
Can you provide a minimal reproducable scenario?

**Comment by monossido** [comment]
up?!
I'm using angular-chartist and I have not understand the workaround

**Comment by SpaceK33z** [comment]
As long as no-one provides a reproducable scenario, I can't fix this.... a PR is also welcome.

**Comment by paul-apacio** [comment]
A reproducible scenario would simply be to attempt to create 3 bar charts, with legends on the same page, but using similar data.

When I had this problem back in April, only the first chart's legend would get rendered.

I worked around this by rendering the legend using plain HTML outside of chartist, but that negates the point of the plugin.

**Comment by SpaceK33z** [comment]
But looking at [the demo](https://codeyellowbv.github.io/chartist-plugin-legend/), this appears to work. Even if I change the `Line` charts there to `Bar` charts, it still works. Can you provide a demo (with JSBin or whatever)?

**Comment by paul-apacio** [comment]
Then it would appear the issue must be fixed.

**Comment by SpaceK33z** [comment]
I'll close this issue for now then. **If anyone still has this issue, please provide a working demo and I'll re-open this.**

**Comment by monossido** [comment]
This bug comes with a different version of the library, if you install the plugin with bower it will download this forked version https://github.com/Pinacono/chartist-plugin-legend
Installing it with npm solved the issue.
