### ISSUE TITLE
how to install plugin in visual studio for chartist

### ISSUE THREAD

**Issue by Zaid-Mirza** [CodeYellowBV/chartist-plugin-legend#20]
Scenario is,

Im making an AngularJS application using Visual Studio 2013.My chartist pie chart is working. I need to add legends. I have added .ct-legend class to my css. My problem is how i can install legend plugin there?

**Comment by Lekensteyn** [comment]
What have you tried? What steps from the README did not work for you?

**Comment by Zaid-Mirza** [comment]
@Lekensteyn yeah I done it, Actually problem was that VS dont have compiler for sass convertor.. Now Ihave  successfully converted sass to css and include your css to my base then I built legends in Html.Thanks
