### ISSUE TITLE
chartist-plugin-legend compatibility with new version of chartist

### ISSUE THREAD

**Issue by preetcam** [CodeYellowBV/chartist-plugin-legend#21]
I updated my project with new version of chartist 0.9.8, but seems like legends plugin is not compatibility with this version.

If I use old version of legend plugin, I get two graphs per widget. 
But new version of legends plugin is not compatible. I am getting error saying chartist-plugin-legend is not a function and $ is not defined.

**Comment by ajdust** [comment]
I am on 0.9.8 with no problems. Perhaps a specific use stopped working?

$ sounds like a jQuery selector - both chartist and this plugin don't have any dependencies on jQuery or otherwise and shouldn't be using $.

**Comment by preetcam** [comment]
As soon as I update my chartist version to 0.9.8, My graphs starts splitting. 
I observed the legend plugin version is not compatible. If I remove Legends, the code works fine. 
But I need to use display legends too in my graph. 

I tried updating legend version too. it dint help.
<img width="954" alt="screen shot 2016-08-01 at 4 01 08 pm" src="https://cloud.githubusercontent.com/assets/4131188/17311586/43cfeb92-5801-11e6-9bcc-47d9bb089bd8.png">

**Comment by SpaceK33z** [comment]
[The demo](https://codeyellowbv.github.io/chartist-plugin-legend/) also uses 0.9.8 now, and I don't see any problems. Can you upload a minimal example to jsfiddle / codepen? I'll take a look then.

**Comment by preetcam** [comment]
Can you help me how can I use the legends plugin to support for Angular Application.

I see the code in latest Legend Plugin : 
module.exports = factory(require('chartist'), require('jquery'));

As my project is in Angular, its not supporting jquery. 
When ever I run legend plugin, I get error saying $ is not defined.

**Comment by preetcam** [comment]
Just an update, my issue got resolved. 
Resolution : I downloaded the jquery earlier but this time I included/added  jquery file in plugins folder. By this the jQuery tags are no issue :) 
Thanks for your help.
