### ISSUE TITLE
Placing legend in custom location

### ISSUE THREAD

**Issue by Kinetic-Pulse** [CodeYellowBV/chartist-plugin-legend#22]
Hey There,
Awesome plugin and thank you for making this available.

I saw a previous closed issue about moving the legend using custom css.
Probably a noob question but how would I with css place the legend below the chart?

Thanks again.

**Comment by ajdust** [comment]
I don't know about CSS - there probably is some fancy way to switch element positions. But it may be simpler and more maintainable to do it in JavaScript.

Currently the plugin appends to the chart container before the chart itself is drawn, so the legend is above the chart. I see two options..
- Switch the positions after the fact at some point. Something like `$('.ct-legend').insertAfter($('.ct-legend').next())` will work to put the legend on the bottom.
- Fork the plugin (recommended if you anticipate needing to make more changes to legends, this plugin is very small and rudimentary). Replace the line `chart.container.appendChild(legendElement);` with `chart.on('draw', function () { chart.container.appendChild(legendElement); });
  ` to append the legend after the chart draws (put the legend below).

**Comment by tarekis** [comment]
Adding a option for side positioning would be quite sweet IMHO, until now i personally solved this with a CSS hack:

```
transform: translateY(yourChartsHeightInPx)
```

**Comment by SpaceK33z** [comment]
A PR is welcome, I don't have time to fix this myself atm.

**Comment by tarekis** [comment]
Gonna make a PR soon in this case.
