### ISSUE TITLE
Legend Colors

### ISSUE THREAD

**Issue by carolgomesm** [CodeYellowBV/chartist-plugin-legend#32]
The color of the legends are not being rendered. I can't use SASS on my project. Is there a way to show to correct colors without SASS?

**Comment by SpaceK33z** [comment]
Yes, a way to do this is go to http://www.sassmeister.com/, then copy paste [this line](https://github.com/gionkunz/chartist-js/blob/develop/src/styles/settings/_chartist-settings.scss#L71) and then copy paste the Sass from this README under it. SassMeister should give you the CSS output.

**Comment by carolgomesm** [comment]
Thanks!
