### ISSUE TITLE
Lack Examples

### ISSUE THREAD

**Issue by jhnmrls** [CodeYellowBV/chartist-plugin-legend#35]
It's better to isolate your examples on a separate html page per capability.

**Comment by SpaceK33z** [comment]
Why? The example page has code samples that you can copy/paste. If you really want to, please make a PR.

**Comment by jhnmrls** [comment]
> The example page has code samples that you can copy/paste

That is true, but it's just a code snippet, I had to do a lot of research (checking prev. issues), to get what I wanted. (Percentage + LegendName to be exact).

+ the CSS snippet you posted, doesn't work on my page. It would be easy to check if there's a working example page in isolation.
