### ISSUE TITLE
Worng data to final chart

### ISSUE THREAD

**Issue by Jeketerri** [CodeYellowBV/chartist-plugin-legend#39]
I have a problem, maybe is caused by a bad building:

                console.log('arr_data ' + arr_data);
                obj = { "name": tara_fin[i], "data": arr_data };
                arr_series.push(obj);

I get this data output:

```
arr_data 36,27
arr_data 18,9
arr_data 9,9
arr_data 9,48
arr_data 36,24
arr_data 12,12
arr_data 12,12
```

But in the graph I only get all the bars with the last array information, the labels are okey, w/o the box color border, but it works.
Sorry with my very bad English, and thanks for the response.

**Comment by SpaceK33z** [comment]
I don't understand... Please provide a [CodePen](http://codepen.io/) where you reproduce your issue.

**Comment by Jeketerri** [comment]
Hi, sorry for the lateness, I'm registered now on the codepen, but I don't know why it doesn't work with my script, sorry I learn to code this year, [this is the code](https://codepen.io/Jeketerri/pen/YZmjrQ), Well I simplified the code, because I recover the data from an AJAX call.

**Comment by Jeketerri** [comment]
Well, I found the problem in the codepen, it was on the CDN of your plugin, you can see now how my graph apear, it only get the last data I pass, I don't know if a problem of your plugin or is in my building... sorry for my bad English :(

**Comment by SpaceK33z** [comment]
I'm sorry but I don't have time for this. I would recommend asking this on [StackOverflow](https://stackoverflow.com/).
