### ISSUE TITLE
Request: Output value next to label

### ISSUE THREAD

**Issue by mattgreenfield** [CodeYellowBV/chartist-plugin-legend#4]
Hi, thanks for making this great plugin.

Is there or could there be a simple way to output the value next to the legend?

For example, I have a pie chart and want to put the percentage value on the legend;
<img width="235" alt="screenshot 2016-01-28 17 07 39" src="https://cloud.githubusercontent.com/assets/7290654/12652214/ac495788-c5e1-11e5-8c5e-6c280e7de82e.png">

Thanks again,

**Comment by SpaceK33z** [comment]
You can pass an option, `legendNames` to specify what you want in that.

E.g.

``` js
Chartist.plugins.legend({ legendNames: ['this', 'something', 'something else'] })
```

**Comment by mattgreenfield** [comment]
Ah, thanks @SpaceK33z , I never got around to trying this but will do.
