### ISSUE TITLE
Using signals and classes

### ISSUE THREAD

**Issue by doctormo** [CodeYellowBV/chartist-plugin-legend#40]
I've made a new fork of chartist-plugin-legend, you can see it in the forks list. It probably shouldn't be merged in as it's a) guts the project code like a fish and b) has a new license.

But I bring it up because the idea of using chartist signals to add and keep legends up to date is worth considering. It's much cleaner to have chartist tell me when a series is being drawn than try and tie lots of indexes together from copied arrays.

**Comment by SpaceK33z** [comment]
Hey, this is an interesting idea. It would also fix #5, which is a nice bonus. Would you mind preparing a PR? Perhaps with an added test that checks if legends are not duplicated (not sure if this is necessary)?

**Comment by doctormo** [comment]
Not sure if I can make a merge request, it's such a large change. I'll post it, but feel free to shoot it down.

**Comment by amichair** [comment]
+1

**Comment by aendu** [comment]
so what is the status here?
As far as i see it, update does still not work. But i might have done something wrong?
Thx for an update.

**Comment by doctormo** [comment]
@aendu - Forked with regret: https://github.com/doctormo/chartist-plugin-legendary
