### ISSUE TITLE
Internet Explorer has stopped working

### ISSUE THREAD

**Issue by chelaruc** [CodeYellowBV/chartist-plugin-legend#47]
The charts are working fine in Chrome, but we got issues on IE. For example when the IE browser is not maximized, and then we maximize it, we got following error ( see screenshot below)

![erroe](https://user-images.githubusercontent.com/22840626/31934423-bee1e578-b8b4-11e7-8afa-ef09fb4baae8.png)

Could you please let me know how this can be fixed?

Best,
Ciprian

**Comment by tarekis** [comment]
Hello Ciprian,

sadly this information does not help me too much investigating the problem's source. Please provide me with the exact version number of your OS, IE, Chartist and the plugin, and most important any JavaScript logs you get with this error.

**Comment by tarekis** [comment]
@chelaruc I am trying to close abandoned issues, if this issue is still relevant, please provide some more information so I can investigate it.

**Comment by chelaruc** [comment]
Hi, @tarekis! I'm sorry I didn't saw your answer until now. I will do a demo project for testing.

**Comment by chelaruc** [comment]
@tarekis it's working now...

**Comment by tarekis** [comment]
Thanks for letting me now, if this occurs again, please reopen the issue and attatch a detailed reproduxtion scenario.
