### ISSUE TITLE
Site doesn't work on firefox

### ISSUE THREAD

**Issue by FelisPhasma** [CodeYellowBV/chartist-plugin-legend#50]
[Screenshot](https://gyazo.com/4f2f84158abe9db08fc36ee6bfce8ec3)

Debug information:
```
TypeError: line.match(...) is null
At chartist-plugin-legend:337:36
Stack trace:
implementAndDocumentFunctionByClass/<    https://codeyellowbv.github.io/chartist-plugin-legend/:337:36
forEach self-hosted:273:13 implementAndDocumentFunctionByClass 
  https://codeyellowbv.github.io/chartist-plugin-legend/:332:10
<anonymous>     https://codeyellowbv.github.io/chartist-plugin-legend/:358:5
```

Browser
`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0`

**Comment by tarekis** [comment]
Oh, well that is an error in the GitHub pages demo, not the plugin itself. I'll fix it when I have some time...

**Comment by FelisPhasma** [comment]
@tarekis Yeah, it's no biggy. I just launched it in another browser and it was all good. If I get a chance I'll take a look at the code too and save you the trouble!

**Comment by tarekis** [comment]
Fixed by https://github.com/CodeYellowBV/chartist-plugin-legend/pull/51.
