### ISSUE TITLE
chart and legend colors don't match after clicking on label 

### ISSUE THREAD

**Issue by MauroJurada** [CodeYellowBV/chartist-plugin-legend#57]
Sorry if this is stupid, I'm new to this.

My issue is that after clicking on a label in legend to hide that entry from the chart the graph colors all update while the colors on legend don't.
![image](https://user-images.githubusercontent.com/37582356/44949355-f90ee900-ae2f-11e8-9acc-36ffa331bb2f.png)
after click:
![image](https://user-images.githubusercontent.com/37582356/44949359-075d0500-ae30-11e8-887c-0027e6554e45.png)

I've also found that on https://codepen.io/chimmer/pen/aJvBgv same happens.

This is the css I use: 
https://pastebin.com/xSF9EJCb
it's pure css, but that shouldn't matter since codepen has the same issue while using less, right?

I would want the chart to not update colors. Do I have to use onClick and manualy update the colors in my css?

**Comment by tarekis** [comment]
That is pretty much just a CSS issue, you can't use the n-th child selector like I did in my pen you linked, but use selectors for the actual series' class names e.g. `.ct-series-b`. I simply copied your CSS and added line styles, you should be able to figure what's happening by that i hope: https://codepen.io/chimmer/pen/QVvMgz.
