### ISSUE TITLE
Legend does not respect chart height in Firefox 

### ISSUE THREAD

**Issue by arvinsingla** [CodeYellowBV/chartist-plugin-legend#9]
When the legend plugin is enabled and a height is explicitly set in the chartist options something strange happens. The chart expands outside the height boundary and cuts off. This is occurring only in Firefox and only when height is set. Tested on Firefox 42 and 44.

Expected results (Chrome, Safari, IE11)

<img width="1002" alt="screen shot 2016-02-03 at 11 46 49 am" src="https://cloud.githubusercontent.com/assets/645082/12789729/07eafdd2-ca6d-11e5-8918-0b8eea7daadc.png">

Unexpected result (Firefox)

<img width="1002" alt="screen shot 2016-02-03 at 11 47 01 am" src="https://cloud.githubusercontent.com/assets/645082/12789734/0f2ffa66-ca6d-11e5-9c95-ec0b1ec732d4.png">

Example configuration used to generate this chart:

``` javascript
var options = {
  showPoint: true,
  height: 100,
  axisX: {
    type: Chartist.AutoScaleAxis,
  },
  plugins: [
    Chartist.plugins.legend()
  ]
};
```

**Comment by arvinsingla** [comment]
After some more testing turns out it is not related to the height property and is in fact always occurring in Firefox. It is just more noticeable when height is set.

**Comment by SpaceK33z** [comment]
The [demo](https://codeyellowbv.github.io/chartist-plugin-legend/) also has this bug.

**Comment by arvinsingla** [comment]
Did some more digging and it turns out it's an issue with Firefox's SVG rendering which Chartist does account for. Firefox is unable to properly determine the height of the SVG element so Chartist in it's `height()` function has a fall back to set the height equal to it's container element.

The problem arises because the legend is being injecting that container which in turn alters the height. So if for example the height of the container was 100px the height of the chart would be set to 100px because of this fallback, but when legend gets injected the height changes, and the chart gets set to this new changed height. So you have a container that is now larger (e.g. 118px), but contains both the legend and a chart that is also set to 118px. So the bottom of the SVG gets cut off.

I ended up getting around this using CSS by setting `position: relative;` on the legend and placing a negative bottom margin `magin-bottom: -18px;` equal to the height of the legend. Then I added a margin top `margin-top: 18px;`to the container equal to the legend height as well. The net effect being that the height of the container stays the same so the chart renders correctly.

Since this is a browser issue there's not much that can be done with the plugin, however might be worth while to make users aware of it and have sample CSS as a workaround.

**Comment by SpaceK33z** [comment]
Thanks for debugging this issue! Using a negative bottom margin is a nice workaround, but not a nice solution.
Maybe this plugin should also use SVG to insert the legend items? I'm not sure since it would be somewhat more difficult to style it exactly like you want.

**Comment by SpaceK33z** [comment]
Interesting, after upgrading to chartist 0.9.7 it seems to be fixed. It probably was this issue: gionkunz/chartist-js/issues/592
